version: "2"
linters:
  enable:
    - asciicheck
    - bodyclose
    - dogsled
    - gocognit
    - godox
    - gomodguard
    - misspell
    - nakedret
    - nestif
    - noctx
    - predeclared
    - staticcheck
    - unconvert
    - unparam
    - whitespace
    - wsl
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
